services:
  hr-ops-portal-backend-dev:
    container_name: hr-ops-portal-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8000:3000'
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - hr-ops-portal-mysql
    command: ['sh', '-c', 'pnpm exec prisma generate && pnpm run start:dev']
    networks:
      - hr-ops-portal-network

  hr-ops-portal-mysql:
    container_name: hr-ops-portal-mysql
    image: mysql:8.0
    ports:
      - '3307:3306'
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-mysql.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - hr-ops-portal-network

volumes:
  mysql_data:

networks:
  hr-ops-portal-network:
    external: true
